spring:
    datasource:
     url: jdbc:h2:file:C:/h2data/sample # jdbc:mysql://localhost:3306/account_db
     username: sa #root
     password: #root
     driver-class-name: org.h2.Driver # com.mysql.cj.jdbc.Driver
    h2:
     console:
      enabled: true
      path: /h2
      
    jpa:
     show-sql: true
     generate-ddl: true
     #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect     hibernate:        ddl-auto: update
    jackson:
      serialization:
        fail-on-empty-beans: false
        
    application:
     name: account-service
    
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
        
server:  port: 2222