spring:
  datasource:
    url: jdbc:h2:file:C:/h2data/sample_notification #jdbc:mysql://localhost:3306/bankapp
    username: sa #root
    password: #root
    driver-class-name: org.h2.Driver # com.mysql.cj.jdbc.Driver
  h2:
    console:
     enabled: true
     path: /h2

  application:
    name: notification-service
        
  jpa:
      show-sql: true
      generate-ddl: true
      #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate:
        ddl-auto: update
      jackson:
        serialization:
         fail-on-empty-beans: false
    
server:  port: 3038
  
  
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka   
    
   