spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bankapp
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: notification-service
        
  jpa:
      show-sql: true
      generate-ddl: true
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate:
        ddl-auto: update
    
server:  port: 3038
  
  
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka   
    
   