spring:
  datasource:
    url: jdbc:mysql://localhost:3306/loan
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    
    
  jpa:
   show-sql: true
   hibernate:
     ddl-auto: update
   database-platform: org.hibernate.dialect.MySQL8Dialect   
  application:
   name: customer-service
  

server:
   port: 4040

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true        
    
    
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"    